### ISSUE TITLE
Screen of my phone has black bars

### ISSUE THREAD

**Issue by dannyboiii69** [MerlionRock/RealAndroidBot#24]
I recently tried to connect my phone to the RAB.exe console but when it detected my screen resolution, my screen shrunk in size and now I have black bars on the top and bottom of my screen and it won't go away. I've had to contact OnePlus and they don't even know what went wrong.

![WIN_20210408_11_54_21_Pro](https://user-images.githubusercontent.com/70595964/114011838-f9808380-9865-11eb-8162-fbf80cf6ecd4.jpg)

I hope this is a common issue and can be sorted out easily because I have been searching the net with no luck.

**Comment by MerlionRock** [comment]
Connect your phone to your computer, run RAB.exe again. Go to the tool tab (Last Tab) and click on "Reset Phone Resolution".

If you cannot see the option, ensure your computer resolution is 1920x1080 or more

Instructions has been clearly stated right at the start when you start up RAB,exe
"Remember to use CTRL+C when you want to quit RAB"

Please ensure you did that again to prevent your phone stuck in smaller resolution

**Comment by dannyboiii69** [comment]
It says device 'None' not found in the terminal

**Comment by MerlionRock** [comment]
Make sure your phone is properly connected and screen is unlocked.

**Comment by dannyboiii69** [comment]
Thank you so much for the help. I was being stupid when reading through the instructions. Thank you again!

I was super worried for a second there.

**Comment by MerlionRock** [comment]
More warning will be added in new version to prevent this from happening again. This issue will be closed.

**Comment by Fai1edMit0sis** [comment]
This just happened with my phone. I connected it back and tried what you said, but it's not working. Is it stuck forever in this?
