### ISSUE TITLE
Offset Value NOT Found

### ISSUE THREAD

**Issue by goldentoxicspenc** [MerlionRock/RealAndroidBot#41]
I am running on a pixel 3 with PGSharp, after configuring the app and launching, I receive this. And nothing happens. My device gets "tapped" a few times then nothing happens.

Please wait... checking offset...
 Offset Value NOT Found. Your phone might be incompatible with RAB!
Last Login: 26 Jun 2021, 23:50:03
Starting logcat ['adb', '-s', '96CX21FF6', 'logcat', '-T', '1', '-v', 'brief', 'MainService:D j:D ClipboardReceiver:D *:S']
 Starting logcat ['adb', '-s', '96CX21FF6', 'logcat', '-T', '1', '-v', 'brief', 'MainService:D j:D ClipboardReceiver:D *:S']

**Comment by wingchangwow** [comment]
Same issue happening here on Samsung Galaxy A7 with PGSharp

**Comment by MerlionRock** [comment]
Try the latest v1.3.1 and let me know if problem has been solved.

**Comment by rladlb** [comment]
Same issue for me on P30 lite ans RAB 1.31


`Offset Value NOT Found. Your phone might be incompatible with RAB!`

**Comment by MerlionRock** [comment]
If you recieved the message: incompatible, it means incompatible. 

Alternatively try full screen gesture mode of your phone. if there's gesture hint, disable it. Any further question, ask in discord.
