### ISSUE TITLE
INFO    | Failed to load SSL library: <class 'OSError'> (no library called "ssl" found)

### ISSUE THREAD

**Issue by CritSin** [MerlionRock/RealAndroidBot#45]
What is that ?
How can i resolve ?
21:04:41.206 INFO    | Failed to load SSL library: <class 'OSError'> (no library called "ssl" found)

**Comment by Neoples** [comment]
Enable Usb Debugging on your phone. İf you use xiaomi, Enable debugging security also.

**Comment by CritSin** [comment]
debugging is enable. Phone is huawei p30 lite

**Comment by rladlb** [comment]
Same issue for me on a P30 lite too

**Comment by MerlionRock** [comment]
RAB will still work despite that error.
If it doesn't, report the error AFTER that.
