### ISSUE TITLE
Not working with Xiaomi Mi 9T

### ISSUE THREAD

**Issue by Gengar09** [MerlionRock/RealAndroidBot#47]
I've tried a lot of things but app didn't work. Please help me.

![Adsız](https://user-images.githubusercontent.com/20893622/125513977-57bbc9c8-8b8e-4edc-ae5d-1e626adf5759.jpg)

**Comment by Gengar09** [comment]
@MerlionRock please answer me ASAP

**Comment by MerlionRock** [comment]
Enable USB Debugging (security setting).

There are two USB debugging settings for xiaomi phone. If still can't work, ask in discord.

This will be closed as there are no additional console log.

**Comment by Gengar09** [comment]
Can you write your discord link?
