### ISSUE TITLE
Script Activation Failed

### ISSUE THREAD

**Issue by sandycabaal** [MerlionRock/RealAndroidBot#6]
PS C:\WINDOWS\system32> cd c:\
PS C:\> git clone --recursive http://github.com/MerlionRock/RealAndroidBot.git
Cloning into 'RealAndroidBot'...
warning: redirecting to https://github.com/MerlionRock/RealAndroidBot.git/
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 481 (delta 44), reused 32 (delta 7), pack-reused 391R
Receiving objects: 100% (481/481), 5.33 MiB | 587.00 KiB/s, done.
Resolving deltas: 100% (214/214), done.
PS C:\> python3 -m venv RealAndroidBot
PS C:\> RealAndroidBot\Scripts\activate
RealAndroidBot\Scripts\activate : The module 'RealAndroidBot' could not be loaded. For more information, run
'Import-Module RealAndroidBot'.
At line:1 char:1
+ RealAndroidBot\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RealAndroidBot\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

PS C:\> Set-ExecutionPolicy RemoteSigned

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): y
PS C:\> RealAndroidBot\Scripts\activate
RealAndroidBot\Scripts\activate : The module 'RealAndroidBot' could not be loaded. For more information, run
'Import-Module RealAndroidBot'.
At line:1 char:1
+ RealAndroidBot\Scripts\activate
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (RealAndroidBot\Scripts\activate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule
![Capture1](https://user-images.githubusercontent.com/78262520/106357001-802a5900-6329-11eb-812f-85aafd0d22fe.PNG)

**Comment by MerlionRock** [comment]
Please enter this command before proceeding `Set-ExecutionPolicy Unrestricted` let me know if it works

**Comment by Darkatek7** [comment]
I think you can close this now ;)
