### ISSUE TITLE
The term 'C:\RealAndroidBot' is not recognized

### ISSUE THREAD

**Issue by J05hu94** [MerlionRock/RealAndroidBot#7]
Chocolatey v0.10.15
Installing the following packages:
visualstudio2019-workload-vctools
By installing you accept licenses for the packages.
visualstudio2019-workload-vctools v1.0.0 already installed. Forcing reinstall of version '1.0.0'.
 Please use upgrade if you meant to upgrade to a new version.
Progress: Downloading visualstudio2019-workload-vctools 1.0.0... 100%

visualstudio2019-workload-vctools v1.0.0 (forced) [Approved]
visualstudio2019-workload-vctools package files install completed. Performing other installation steps.
Installing visualstudio2019-workload-vctools...

...install...

2021-01-30T08:33:27 : Verbose : Calling SetupEngine.Installer.ModifyProduct. [installationPath: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools']

(node:3336) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2021-01-30T08:46:24 : Verbose : SetupEngine.Installer.ModifyProduct succeeded. [installationPath: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools']

2021-01-30T08:46:24 : Verbose : Closing installer. Return code: 0.

2021-01-30T08:46:24 : Verbose : Closing installer. Return code: 0.

2021-01-30T08:46:25 : Verbose : [ProductsProviderImpl]: Rpc connection was closed.

2021-01-30T08:46:25 : Verbose : [ProductsProviderImpl]: Stream was closed

2021-01-30T08:46:25 : Verbose : [InstalledProductsProviderImpl]: Rpc connection was closed.

2021-01-30T08:46:25 : Verbose : [InstalledProductsProviderImpl]: Stream was closed

2021-01-30T08:46:25 : Verbose : [InstallerImpl]: Rpc connection was closed.

2021-01-30T08:46:25 : Verbose : [InstallerImpl]: Stream was closed

visualstudio2019-workload-vctools has been installed.
  visualstudio2019-workload-vctools may be able to be automatically uninstalled.
 The install of visualstudio2019-workload-vctools was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
C:\RealAndroidBot : The term 'C:\RealAndroidBot' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ C:\RealAndroidBot
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\RealAndroidBot:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32> PowerShell -NoExit "C:\RealAndroidBot"
C:\RealAndroidBot : The term 'C:\RealAndroidBot' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ C:\RealAndroidBot
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\RealAndroidBot:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Windows\system32> cd python3 -m venv RealAndroidBot
Set-Location : A parameter cannot be found that matches parameter name 'm'.
At line:1 char:12
+ cd python3 -m venv RealAndroidBot
+            ~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

**Comment by MerlionRock** [comment]
`cd c:\` first before execute `python3 -m venv RealAndroidBot`

Please see my command carefully. There is no CD in front of python

**Comment by MerlionRock** [comment]
Closing issue. Latest PR solve this issue.

**Comment by J05hu94** [comment]
my mistake i thought the problem lied with the C:\RealAndroidBot : The term 'C:\RealAndroidBot' is not recognized
because that was where my first error occurred
